### ISSUE TITLE
Absolute position for the loader & scroll

### ISSUE THREAD

**Issue by Thiktak** [bastinald/laravel-livewire-loader#1]
Hi,

Your loader is working well, but you created it with an absolute position.
When we have more than 100vw, the spinner is scrolling with the page.

Is it possible to use **fixed** position (or allow configuration for position and/or coordinates (bottom-center, top-right, etc ...), instead ?

Thanks.

**Comment by bastinald** [comment]
Yes! I am literally fixing that right now, and also fixing an issue where the loader stays on multiple fast requests.

Will be releasing within the next half hour.

**Comment by bastinald** [comment]
Fixed in version `2.1.1`, make sure you run `composer update` then `npm run dev`.

I also made a bunch of tweaks to my other packages, a clean install might be best if you're just tinkering right now.
